# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Acloud < Formula
  desc "Official CLI for Aruba Cloud — manage cloud resources from the terminal"
  homepage "https://github.com/Arubacloud/acloud-cli"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Arubacloud/acloud-cli/releases/download/v0.4.0/acloud_0.4.0_darwin_amd64.tar.gz"
      sha256 "bcb4a6dbad2ffd63f3a4300d802786ecc79d0bc707f53a27331add8c26261990"

      define_method(:install) do
        bin.install "acloud"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Arubacloud/acloud-cli/releases/download/v0.4.0/acloud_0.4.0_darwin_arm64.tar.gz"
      sha256 "3bbfb1a401d89bb59591134b7605f037870c30f6ed6361c80d78edefb899264b"

      define_method(:install) do
        bin.install "acloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Arubacloud/acloud-cli/releases/download/v0.4.0/acloud_0.4.0_linux_amd64.tar.gz"
      sha256 "3f74f05f08ab45c715b9663f3cf0e036847d329ae05e1101ae03f0e055e2b5b0"
      define_method(:install) do
        bin.install "acloud"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Arubacloud/acloud-cli/releases/download/v0.4.0/acloud_0.4.0_linux_arm64.tar.gz"
      sha256 "8616258d20b9a42a06c16240e2c518132c091609f191137ac932ee41e2c52591"
      define_method(:install) do
        bin.install "acloud"
      end
    end
  end

  test do
    system "#{bin}/acloud", "--version"
  end
end
