# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Acloud < Formula
  desc "Official CLI for Aruba Cloud — manage cloud resources from the terminal"
  homepage "https://github.com/Arubacloud/acloud-cli"
  version "0.5.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Arubacloud/acloud-cli/releases/download/v0.5.1/acloud_0.5.1_darwin_amd64.tar.gz"
      sha256 "d45ac3a063aed45d8f8f3affb9fae61146be958410a01fd51f5b617d7911ae58"

      define_method(:install) do
        bin.install "acloud"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Arubacloud/acloud-cli/releases/download/v0.5.1/acloud_0.5.1_darwin_arm64.tar.gz"
      sha256 "9ca0beaf8a6bab55682a23853aa790ceaee808facb6467fd951eaabdd70c32cd"

      define_method(:install) do
        bin.install "acloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Arubacloud/acloud-cli/releases/download/v0.5.1/acloud_0.5.1_linux_amd64.tar.gz"
      sha256 "5b61e17ec7b69f41b84df00be0844a9bc1fc59fd72e08a7ad45c70991bd76896"
      define_method(:install) do
        bin.install "acloud"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Arubacloud/acloud-cli/releases/download/v0.5.1/acloud_0.5.1_linux_arm64.tar.gz"
      sha256 "ee9305d5149c5a5eb3691c1280b1cd72c808287390f6ac04eb06f50363e0203a"
      define_method(:install) do
        bin.install "acloud"
      end
    end
  end

  test do
    system "#{bin}/acloud", "--version"
  end
end
