# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Acloud < Formula
  desc "Official CLI for Aruba Cloud — manage cloud resources from the terminal"
  homepage "https://github.com/Arubacloud/acloud-cli"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Arubacloud/acloud-cli/releases/download/v1.0.0/acloud_1.0.0_darwin_amd64.tar.gz"
      sha256 "b38260f8991e10dd9002a5d88cf05198210d778556aa24972e5cc657ddb4ff5d"

      define_method(:install) do
        bin.install "acloud"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Arubacloud/acloud-cli/releases/download/v1.0.0/acloud_1.0.0_darwin_arm64.tar.gz"
      sha256 "ddb33335b0bdd6ae1515ffe8ce4b5361bf654ae23a0c852fdb05dbceaf46ee95"

      define_method(:install) do
        bin.install "acloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Arubacloud/acloud-cli/releases/download/v1.0.0/acloud_1.0.0_linux_amd64.tar.gz"
      sha256 "da59431f1b21f432ae92d3198f0db10d55a6dcc433395614178e8398a44d65ca"
      define_method(:install) do
        bin.install "acloud"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Arubacloud/acloud-cli/releases/download/v1.0.0/acloud_1.0.0_linux_arm64.tar.gz"
      sha256 "edb80caba410378248ef7e5fa93008649da3b3313f96e67e1e65a07ae46e6103"
      define_method(:install) do
        bin.install "acloud"
      end
    end
  end

  test do
    system "#{bin}/acloud", "--version"
  end
end
